name: "Bug report"
description: "Report a bug in the cookiecutter template."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Exact cookiecutter command and what happened.
      placeholder: |
        1. cookiecutter gh:owner/repo ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Python:
        - cookiecutter:
        - uv: