name: "Feature request"
description: "Suggest an enhancement to the template."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale / use-case
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed change
    validations:
      required: false